Bump R register once per M1 cycle for programs that depend on R incrementing
MockbaTheBorg/RunCPM pull request #128
Opened 2021-06-05 21:48 UTC by ethandicks

Some CP/M applications read the refresh register and use the results as a random number seed.  In one specific case, not only is there no randomness if you don't increment R on each M1 cycle (like a real Z-80), the program actually hangs because it's waiting to read a value greater than 1.

This patch adds an increment to R at each point in the instruction dispatch that corresponds to incrementing R once for every M1 cycle that would have been generated in a real Z-80.  A simple random number generator application does generate random numbers and the aforementioned CP/M application runs as expected.

2021-06-06 11:45 UTC, MockbaTheBorg requested changes
I like this one. Thank you very much.
I would prefer it to be based on a define like "#if defined INCR".
This way people who don't want to use it could filter it out.
It does at least one increment per instruction, so we need to check the performance impact. Some folks might not care about the extra functionality in favor of performance. 
Might I ask: can you share details of which app fails to run when R is not incrementing?
Thanks.
Please make the changes, I will merge.

2021-06-06 13:43 UTC, prlaba commented
Note that only bits 6:0 of the R register are incremented (0x00 to 0x7F) during an M1 cycle.  Bit 7 of the R register is typically unused (0) but can be read or written using the LD A,R and LD R,A instructions.

Also, note that for double-prefix instructions (DDCB and FDCB), each prefix opcode is read using an M1 cycle but the main opcode is read using a normal Memory Read cycle (M1 status line is not activated).  So a total of two R-register increments for double-prefix instructions, same as for single-prefix instructions.

2021-06-06 13:56 UTC, MockbaTheBorg commented
I wonder if on an emulator like RunCPM we really need to be precise in terms of how many times we increment or just give it a single increment per pass. After all we are not really refreshing any dram.

2021-06-06 14:13 UTC, prlaba commented
I don’t know.  There was lots of code written that took advantage of some of the more obscure features of the Z80.

I’d think you’d be fine incrementing the R register once per “pass”, although I recommend limiting the increment to bits 6:0 (wrap at 0x3F) and leave bit 7 unchanged.

2021-06-06 14:16 UTC, prlaba commented
Oh, and if you can easily differentiate between prefixed and non-prefixed instructions, I recommend incrementing the R register _twice_ for the prefixed instructions, and once for the non-prefixed instructions.

2021-06-06 14:21 UTC, prlaba commented
And using a compiler constant to control incrementing the R register is a good idea, as users can then decide if they want to trade off performance for the feature (you could turn off the feature by default).

Of course, your Z80 emulator is already ridiculously fast, so I doubt the additional code to increment the R register will be noticeable.

2021-06-06 15:49 UTC, MockbaTheBorg commented
Makes sense

On Sun, Jun 6, 2021, 10:13 AM prl519 ***@***.***> wrote:

> I don’t know. There was lots of code written that took advantage of some
> of the more obscure features of the Z80.
>
> I’d think you’d be fine incrementing the R register once per “pass”,
> although I recommend limiting the increment to bits 6:0 (wrap at 0x3F) and
> leave bit 7 unchanged.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/MockbaTheBorg/RunCPM/pull/128#issuecomment-855406003>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD74NCYJVTOJG2SCGYU272DTRN7BRANCNFSM46FBV54A>
> .
>

2021-06-06 16:21 UTC, ethandicks commented
I will make the change as requested.

The reason for the specific number of increments is to mirror what a real Z-80 does in terms of how many M1 cycles there are for each instruction.  The impact is how fast R changes as the code runs which would affect what random numbers are generated.

This is not the first emulator I have added this functionality to.  The scheme employed here (INCR(1) or INCR(2)) is the same for the altairz80 emulator in simh (added in V4.0)  The CPU emulation code in altairz80 is not identical to cpu.h here but the flow is largely the same.

The specific program that I have that relies on this behavior is the game engine for Scott Adams Adventures (Adventureland, Pirate's Adventure, Mission Impossible, The Count, etc.)  I'm about to put this program up on the Interactive Fiction Archive and will be including a list of what emulators it has been tested against.

2021-06-06 16:35 UTC, ethandicks commented
Here is a program (which I'm happy to contribute to the library of CP/M programs) that will check the CPU type and if it's a Z-80, use LD A,R to generate random numbers.  If R does not increment, you'll get 0 every time.

`TITLE	'rndtst - test - Test R register as random number generator'
; 26-Dec-2016 <ethan.dicks@gmail.com>
ORG	100H
;
BDOS	EQU	5	;BDOS entry point
COUT	EQU	2	;BDOS Output character
CR	EQU	13
LF	EQU	10
;
START:
	LXI	H,INTRO	;address of intro string
	CALL	STROUT
;
	LXI	H,ITSA	;address type message string
	CALL	STROUT
	XRA	A	;zero A
	DCR	A
	JPE	NOTZ80
	LXI	H,NMZ80	;address Z80 string
	CALL	STROUT
	CALL	CRLF
	JMP	DORND
NOTZ80:	LXI	H,NM8080	;address 8080 string
	CALL	STROUT
	CALL	CRLF
	RET
;
DORND:	CALL	TSTRND
	CALL	TSTRND
	CALL	TSTRND
	CALL	TSTRND
	CALL	TSTRND
	
	RET		;return to CCP

;
; TSTRND - get random number and print it
;
TSTRND:	LXI	H,0
	DB	0EDH, 5FH	; LD A,R in hex for 8080 ASM
	MOV	L,A
	CALL	DECPRT
	CALL	CRLF
	RET

;
; DECPRT - print byte in M/HL as decimal number
;
DECPRT:	PUSH	H
	PUSH	D
	PUSH	B
	MVI	B,0	;leading-zero flag
	LXI	D,-10000
	CALL	SUBTR
	LXI	D,-1000
	CALL	SUBTR
	LXI	D,-100
	CALL	SUBTR
	LXI	D,-10
	CALL	SUBTR
	MOV	A,L
	ADI	'0'
	CALL	CHROUT
	POP	B
	POP	D
	POP	H
	RET

;
SUBTR:	MVI	C,'0'-1
SUBT2:	INR	C
	DAD	D
	JC	SUBT2
;
;	SBC	HL,DE
	MOV	A,L
	SUB	E
	MOV	L,A
	MOV	A,H
	SBB	D
	MOV	H,A
;
	MOV	A,C	;get count
;
	CPI	'1'	;less than 1?
	JNC	NZERO	;no
	MOV	A,B	;check flag
	ORA	A	;is set?
	MOV	A,C	;restore count
	RZ	 	;skip leading 0
	CALL	CHROUT
	RET
;set flag on non-zero chars
NZERO:	MVI	B,0FFH
	CALL	CHROUT
	RET

;
; STROUT - print null terminated string
;
STROUT: 
STLOOP:	MOV	A,M
	ORA	A
	JZ	STRDON
	CALL	CHROUT
	INX	H
	JMP	STLOOP
STRDON:
	RET
	

;
; CRLF - print CR and LF
;
CRLF	MVI	A,CR
	CALL	CHROUT
	MVI	A,LF
;
	; FALL THROUGH

;
; CHROUT - print one char via BDOS 2
;
CHROUT:	PUSH	H
	PUSH	A
	MOV	E,A
	MVI	C,COUT
	CALL	BDOS
	POP	A
	POP	H
	RET
;

INTRO:	DB	'RNDTST - Test R register as random number generator', CR, LF, 0
ITSA:	DB	'CPU is a',0
NMZ80:	DB	' Z80',0
NM8080:	DB	'n 8080',0

	END	START
`

2021-06-06 16:45 UTC, ethandicks commented
The requested change has been made.

2021-06-06 17:11 UTC, ethandicks commented
I've also made another update to mask the increment with 0x3f to keep it to bits 0:6

2021-06-06 18:53 UTC, prlaba commented
Good!  And don’t forget those INT ACK and NMI ACK cycles are also M1 cycles, where the R register gets incremented. For interrupt mode M0, it’s possible for the interrupting device to insert a prefixed instruction on the bus (two M1 cycles to fetch), although I’ve never seen that done.  I should confirm that sometime.

2021-06-07 02:20 UTC, ethandicks reviewed
Wrapped INCR definition in ifdef

2021-06-08 01:09 UTC, merged